# Generated by Django 3.1.7 on 2021-04-01 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('abstract', models.CharField(max_length=1000)),
                ('projecttype', models.CharField(choices=[(1, 'Thsesis'), (7, 'Poster'), (6, 'Patent'), (3, 'Publication'), (2, 'Article'), (8, 'Pre Print'), (5, 'Chapter'), (4, 'Conference Paper'), (9, 'Research Internship  Report')], default=1, max_length=5)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.CharField(max_length=8)),
                ('year', models.IntegerField(choices=[(2, 'Second Year'), (3, 'Third Year'), (4, 'Final Year'), (1, 'First Year')])),
                ('projects', models.ManyToManyField(blank=True, to='ECEapp.Project')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
