# Generated by Django 3.1.7 on 2021-04-01 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECEapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='year',
            field=models.IntegerField(choices=[(4, 'Final Year'), (2, 'Second Year'), (3, 'Third Year'), (1, 'First Year')]),
        ),
        migrations.AlterField(
            model_name='project',
            name='projecttype',
            field=models.CharField(choices=[(9, 'Research Internship  Report'), (3, 'Publication'), (5, 'Chapter'), (6, 'Patent'), (1, 'Thsesis'), (4, 'Conference Paper'), (8, 'Pre Print'), (7, 'Poster'), (2, 'Article')], default=1, max_length=5),
        ),
    ]
