# Generated by Django 3.1.7 on 2021-04-01 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECEapp', '0003_auto_20210401_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projecttype',
            field=models.IntegerField(choices=[(6, 'Patent'), (1, 'Thsesis'), (8, 'Pre Print'), (9, 'Research Internship  Report'), (5, 'Chapter'), (3, 'Publication'), (2, 'Article'), (4, 'Conference Paper'), (7, 'Poster')], default=1, max_length=5),
        ),
    ]
