# Generated by Django 3.1.7 on 2021-04-01 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ECEapp', '0004_auto_20210401_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ECEapp.account'),
        ),
        migrations.AlterField(
            model_name='account',
            name='year',
            field=models.IntegerField(choices=[(1, 'First Year'), (2, 'Second Year'), (4, 'Final Year'), (3, 'Third Year')]),
        ),
        migrations.AlterField(
            model_name='project',
            name='projecttype',
            field=models.IntegerField(choices=[(2, 'Article'), (3, 'Publication'), (1, 'Thsesis'), (6, 'Patent'), (8, 'Pre Print'), (4, 'Conference Paper'), (5, 'Chapter'), (7, 'Poster'), (9, 'Research Internship  Report')], default=1),
        ),
    ]
