# Generated by Django 3.1.7 on 2021-04-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECEapp', '0005_auto_20210401_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projecttype',
            field=models.IntegerField(choices=[(7, 'Poster'), (1, 'Thsesis'), (8, 'Pre Print'), (5, 'Chapter'), (2, 'Article'), (6, 'Patent'), (3, 'Publication'), (4, 'Conference Paper'), (9, 'Research Internship  Report')], default=1),
        ),
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ManyToManyField(null=True, to='ECEapp.Account'),
        ),
    ]
