# Generated by Django 3.1.7 on 2021-04-01 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ECEapp', '0006_auto_20210401_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
        migrations.RemoveField(
            model_name='account',
            name='projects',
        ),
        migrations.AddField(
            model_name='account',
            name='projects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ECEapp.project'),
        ),
        migrations.AlterField(
            model_name='account',
            name='year',
            field=models.IntegerField(choices=[(2, 'Second Year'), (3, 'Third Year'), (1, 'First Year'), (4, 'Final Year')]),
        ),
        migrations.AlterField(
            model_name='project',
            name='projecttype',
            field=models.IntegerField(choices=[(6, 'Patent'), (3, 'Publication'), (7, 'Poster'), (5, 'Chapter'), (9, 'Research Internship  Report'), (1, 'Thsesis'), (4, 'Conference Paper'), (2, 'Article'), (8, 'Pre Print')], default=1),
        ),
    ]
