# Generated by Django 3.1.7 on 2021-04-01 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ECEapp', '0007_auto_20210401_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='account',
            name='projects',
        ),
        migrations.AddField(
            model_name='account',
            name='projects',
            field=models.ManyToManyField(blank=True, null=True, to='ECEapp.Project'),
        ),
        migrations.AlterField(
            model_name='account',
            name='year',
            field=models.IntegerField(choices=[(1, 'First Year'), (4, 'Final Year'), (3, 'Third Year'), (2, 'Second Year')]),
        ),
        migrations.AlterField(
            model_name='project',
            name='projecttype',
            field=models.IntegerField(choices=[(5, 'Chapter'), (1, 'Thsesis'), (8, 'Pre Print'), (6, 'Patent'), (4, 'Conference Paper'), (2, 'Article'), (7, 'Poster'), (9, 'Research Internship  Report'), (3, 'Publication')], default=1),
        ),
    ]
