# Generated by Django 3.1.7 on 2021-04-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECEapp', '0008_auto_20210401_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projecttype',
            field=models.IntegerField(choices=[(5, 'Chapter'), (4, 'Conference Paper'), (3, 'Publication'), (2, 'Article'), (8, 'Pre Print'), (9, 'Research Internship  Report'), (7, 'Poster'), (1, 'Thsesis'), (6, 'Patent')], default=1),
        ),
    ]
