# Generated by Django 3.1.7 on 2021-04-09 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECEapp', '0009_auto_20210401_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phoneno', models.IntegerField()),
                ('research', models.CharField(max_length=500)),
                ('pic', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='year',
            field=models.IntegerField(choices=[(1, 'First Year'), (2, 'Second Year'), (3, 'Third Year'), (4, 'Final Year')]),
        ),
        migrations.AlterField(
            model_name='project',
            name='projecttype',
            field=models.IntegerField(choices=[(5, 'Chapter'), (9, 'Research Internship  Report'), (7, 'Poster'), (4, 'Conference Paper'), (3, 'Publication'), (2, 'Article'), (8, 'Pre Print'), (6, 'Patent'), (1, 'Thsesis')], default=1),
        ),
    ]
