# Generated by Django 3.1.7 on 2021-04-09 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECEapp', '0011_auto_20210409_0550'),
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('role', models.IntegerField(choices=[(2, 'Intern'), (1, 'Full Time')])),
                ('doamin', models.IntegerField(choices=[(4, 'Conference Paper'), (6, 'Patent'), (5, 'Chapter'), (1, 'Thsesis'), (8, 'Pre Print'), (3, 'Publication'), (7, 'Poster'), (9, 'Research Internship  Report'), (2, 'Article')])),
                ('pic', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='year',
            field=models.IntegerField(choices=[(2, 'Second Year'), (3, 'Third Year'), (1, 'First Year'), (4, 'Final Year')]),
        ),
        migrations.AlterField(
            model_name='project',
            name='projecttype',
            field=models.IntegerField(choices=[(4, 'Conference Paper'), (6, 'Patent'), (5, 'Chapter'), (1, 'Thsesis'), (8, 'Pre Print'), (3, 'Publication'), (7, 'Poster'), (9, 'Research Internship  Report'), (2, 'Article')], default=1),
        ),
    ]
