# Generated by Django 3.1.7 on 2021-04-09 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECEapp', '0012_auto_20210409_0603'),
    ]

    operations = [
        migrations.CreateModel(
            name='people',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(2, 'Second Year'), (3, 'Third Year'), (4, 'Final Year'), (1, 'First Year'), (5, 'M.TECH'), (6, 'PHD')])),
                ('rollno', models.CharField(max_length=8)),
                ('phoneno', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='year',
            field=models.IntegerField(choices=[(2, 'Second Year'), (3, 'Third Year'), (4, 'Final Year'), (1, 'First Year'), (5, 'M.TECH'), (6, 'PHD')]),
        ),
        migrations.AlterField(
            model_name='company',
            name='doamin',
            field=models.IntegerField(choices=[(1, 'Thsesis'), (5, 'Chapter'), (6, 'Patent'), (3, 'Publication'), (7, 'Poster'), (2, 'Article'), (4, 'Conference Paper'), (8, 'Pre Print'), (9, 'Research Internship  Report')]),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='phoneno',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='projecttype',
            field=models.IntegerField(choices=[(1, 'Thsesis'), (5, 'Chapter'), (6, 'Patent'), (3, 'Publication'), (7, 'Poster'), (2, 'Article'), (4, 'Conference Paper'), (8, 'Pre Print'), (9, 'Research Internship  Report')], default=1),
        ),
    ]
