# Generated by Django 3.1.7 on 2021-04-09 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECEapp', '0013_auto_20210409_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='year',
            field=models.IntegerField(choices=[(1, 'First Year'), (5, 'M.TECH'), (6, 'PHD'), (2, 'Second Year'), (4, 'Final Year'), (3, 'Third Year')]),
        ),
        migrations.AlterField(
            model_name='company',
            name='doamin',
            field=models.IntegerField(choices=[(2, 'ECE-CORE'), (3, 'ANALYST'), (1, 'IT')]),
        ),
        migrations.AlterField(
            model_name='company',
            name='role',
            field=models.IntegerField(choices=[(1, 'Full Time'), (2, 'Intern')]),
        ),
        migrations.AlterField(
            model_name='people',
            name='year',
            field=models.IntegerField(choices=[(1, 'First Year'), (5, 'M.TECH'), (6, 'PHD'), (2, 'Second Year'), (4, 'Final Year'), (3, 'Third Year')]),
        ),
        migrations.AlterField(
            model_name='project',
            name='projecttype',
            field=models.IntegerField(choices=[(9, 'Research Internship  Report'), (5, 'Chapter'), (3, 'Publication'), (1, 'Thsesis'), (8, 'Pre Print'), (6, 'Patent'), (2, 'Article'), (4, 'Conference Paper'), (7, 'Poster')], default=1),
        ),
    ]
