# Generated by Django 3.1.7 on 2021-04-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECEapp', '0014_auto_20210409_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='year',
            field=models.IntegerField(choices=[(2, 'Second Year'), (6, 'PHD'), (3, 'Third Year'), (5, 'M.TECH'), (4, 'Final Year'), (1, 'First Year')]),
        ),
        migrations.AlterField(
            model_name='company',
            name='role',
            field=models.IntegerField(choices=[(2, 'Intern'), (1, 'Full Time')]),
        ),
        migrations.AlterField(
            model_name='people',
            name='year',
            field=models.IntegerField(choices=[(2, 'Second Year'), (6, 'PHD'), (3, 'Third Year'), (5, 'M.TECH'), (4, 'Final Year'), (1, 'First Year')]),
        ),
        migrations.AlterField(
            model_name='project',
            name='projecttype',
            field=models.IntegerField(choices=[(4, 'Conference Paper'), (7, 'Poster'), (5, 'Chapter'), (6, 'Patent'), (8, 'Pre Print'), (1, 'Thsesis'), (3, 'Publication'), (9, 'Research Internship  Report'), (2, 'Article')], default=1),
        ),
    ]
