# Generated by Django 3.1.7 on 2021-04-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECEapp', '0015_auto_20210410_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='year',
            field=models.IntegerField(choices=[(3, 'Third Year'), (6, 'PHD'), (5, 'M.TECH'), (4, 'Final Year'), (2, 'Second Year'), (1, 'First Year')]),
        ),
        migrations.AlterField(
            model_name='company',
            name='doamin',
            field=models.IntegerField(choices=[(1, 'IT'), (3, 'ANALYST'), (2, 'ECE-CORE')]),
        ),
        migrations.AlterField(
            model_name='company',
            name='role',
            field=models.IntegerField(choices=[(1, 'Full Time'), (2, 'Intern')]),
        ),
        migrations.AlterField(
            model_name='people',
            name='year',
            field=models.IntegerField(choices=[(3, 'Third Year'), (6, 'PHD'), (5, 'M.TECH'), (4, 'Final Year'), (2, 'Second Year'), (1, 'First Year')]),
        ),
        migrations.AlterField(
            model_name='project',
            name='projecttype',
            field=models.IntegerField(choices=[(3, 'Publication'), (4, 'Conference Paper'), (5, 'Chapter'), (9, 'Research Internship  Report'), (6, 'Patent'), (8, 'Pre Print'), (1, 'Thsesis'), (7, 'Poster'), (2, 'Article')], default=1),
        ),
    ]
