# Generated by Django 3.1.7 on 2021-04-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECEapp', '0016_auto_20210410_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='year',
            field=models.IntegerField(choices=[(6, 'PHD'), (4, 'Final Year'), (5, 'M.TECH'), (2, 'Second Year'), (1, 'First Year'), (3, 'Third Year')]),
        ),
        migrations.AlterField(
            model_name='company',
            name='doamin',
            field=models.IntegerField(choices=[(2, 'ECE-CORE'), (3, 'ANALYST'), (1, 'IT')]),
        ),
        migrations.AlterField(
            model_name='company',
            name='role',
            field=models.IntegerField(choices=[(2, 'Intern'), (1, 'Full Time')]),
        ),
        migrations.AlterField(
            model_name='people',
            name='year',
            field=models.IntegerField(choices=[(6, 'PHD'), (4, 'Final Year'), (5, 'M.TECH'), (2, 'Second Year'), (1, 'First Year'), (3, 'Third Year')]),
        ),
        migrations.AlterField(
            model_name='project',
            name='projecttype',
            field=models.IntegerField(choices=[(4, 'Conference Paper'), (1, 'Thsesis'), (3, 'Publication'), (7, 'Poster'), (8, 'Pre Print'), (9, 'Research Internship  Report'), (2, 'Article'), (5, 'Chapter'), (6, 'Patent')], default=1),
        ),
    ]
