# Generated by Django 3.1.7 on 2021-04-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECEapp', '0017_auto_20210410_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='year',
            field=models.IntegerField(choices=[(6, 'PHD'), (4, 'Final Year'), (1, 'First Year'), (5, 'M.TECH'), (2, 'Second Year'), (3, 'Third Year')]),
        ),
        migrations.AlterField(
            model_name='company',
            name='doamin',
            field=models.IntegerField(choices=[('MANAGERIAL', 'ANALYST'), ('ECE-CORE', 'ECE-CORE'), ('IT', 'IT')]),
        ),
        migrations.AlterField(
            model_name='company',
            name='role',
            field=models.IntegerField(choices=[('FULL-TIME', 'Full Time'), ('INTERNSHIP', 'Intern')]),
        ),
        migrations.AlterField(
            model_name='people',
            name='year',
            field=models.IntegerField(choices=[(6, 'PHD'), (4, 'Final Year'), (1, 'First Year'), (5, 'M.TECH'), (2, 'Second Year'), (3, 'Third Year')]),
        ),
        migrations.AlterField(
            model_name='project',
            name='projecttype',
            field=models.IntegerField(choices=[(7, 'Poster'), (4, 'Conference Paper'), (1, 'Thsesis'), (6, 'Patent'), (5, 'Chapter'), (8, 'Pre Print'), (3, 'Publication'), (2, 'Article'), (9, 'Research Internship  Report')], default=1),
        ),
    ]
