# Generated by Django 3.1.7 on 2021-04-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECEapp', '0018_auto_20210410_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='year',
            field=models.IntegerField(choices=[(5, 'M.TECH'), (1, 'First Year'), (4, 'Final Year'), (2, 'Second Year'), (6, 'PHD'), (3, 'Third Year')]),
        ),
        migrations.AlterField(
            model_name='company',
            name='doamin',
            field=models.CharField(choices=[('MANAGERIAL', 'ANALYST'), ('IT', 'IT'), ('ECE-CORE', 'ECE-CORE')], max_length=10),
        ),
        migrations.AlterField(
            model_name='company',
            name='role',
            field=models.CharField(choices=[('FULL-TIME', 'Full Time'), ('INTERNSHIP', 'Intern')], max_length=10),
        ),
        migrations.AlterField(
            model_name='people',
            name='year',
            field=models.IntegerField(choices=[(5, 'M.TECH'), (1, 'First Year'), (4, 'Final Year'), (2, 'Second Year'), (6, 'PHD'), (3, 'Third Year')]),
        ),
        migrations.AlterField(
            model_name='project',
            name='projecttype',
            field=models.IntegerField(choices=[(8, 'Pre Print'), (3, 'Publication'), (7, 'Poster'), (4, 'Conference Paper'), (5, 'Chapter'), (2, 'Article'), (9, 'Research Internship  Report'), (1, 'Thsesis'), (6, 'Patent')], default=1),
        ),
    ]
