# Generated by Django 3.1.7 on 2021-04-10 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECEapp', '0019_auto_20210410_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='elegibilty',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='projects',
            field=models.ManyToManyField(blank=True, to='ECEapp.Project'),
        ),
        migrations.AlterField(
            model_name='account',
            name='year',
            field=models.IntegerField(choices=[(3, 'Third Year'), (1, 'First Year'), (2, 'Second Year'), (6, 'PHD'), (4, 'Final Year'), (5, 'M.TECH')]),
        ),
        migrations.AlterField(
            model_name='company',
            name='doamin',
            field=models.CharField(choices=[('IT', 'IT'), ('ECE-CORE', 'ECE-CORE'), ('MANAGERIAL', 'ANALYST')], max_length=10),
        ),
        migrations.AlterField(
            model_name='people',
            name='year',
            field=models.IntegerField(choices=[(3, 'Third Year'), (1, 'First Year'), (2, 'Second Year'), (6, 'PHD'), (4, 'Final Year'), (5, 'M.TECH')]),
        ),
        migrations.AlterField(
            model_name='project',
            name='projecttype',
            field=models.IntegerField(choices=[(5, 'Chapter'), (4, 'Conference Paper'), (9, 'Research Internship  Report'), (7, 'Poster'), (1, 'Thsesis'), (6, 'Patent'), (3, 'Publication'), (2, 'Article'), (8, 'Pre Print')], default=1),
        ),
    ]
