# Generated by Django 3.1.7 on 2021-04-10 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECEapp', '0020_auto_20210411_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='doamin',
            field=models.CharField(choices=[('IT', 'IT'), ('MANAGERIAL', 'ANALYST'), ('ECE-CORE', 'ECE-CORE')], max_length=10),
        ),
        migrations.AlterField(
            model_name='company',
            name='role',
            field=models.CharField(choices=[('INTERNSHIP', 'Intern'), ('FULL-TIME', 'Full Time')], max_length=10),
        ),
        migrations.AlterField(
            model_name='people',
            name='year',
            field=models.IntegerField(choices=[(3, 'Third Year'), (6, 'PHD'), (2, 'Second Year'), (4, 'Final Year'), (5, 'M.TECH'), (1, 'First Year')]),
        ),
        migrations.AlterField(
            model_name='project',
            name='projecttype',
            field=models.IntegerField(choices=[(7, 'Poster'), (4, 'Conference Paper'), (2, 'Article'), (9, 'Research Internship  Report'), (6, 'Patent'), (5, 'Chapter'), (8, 'Pre Print'), (3, 'Publication'), (1, 'Thsesis')], default=1),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
