# Generated by Django 3.1.7 on 2021-04-10 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECEapp', '0021_auto_20210411_0328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('url', models.URLField()),
                ('desc', models.TextField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='doamin',
            field=models.CharField(choices=[('IT', 'IT'), ('ECE-CORE', 'ECE-CORE'), ('MANAGERIAL', 'ANALYST')], max_length=10),
        ),
        migrations.AlterField(
            model_name='people',
            name='year',
            field=models.IntegerField(choices=[(5, 'M.TECH'), (6, 'PHD'), (4, 'Final Year'), (2, 'Second Year'), (3, 'Third Year'), (1, 'First Year')]),
        ),
        migrations.AlterField(
            model_name='project',
            name='projecttype',
            field=models.IntegerField(choices=[(2, 'Article'), (9, 'Research Internship  Report'), (1, 'Thsesis'), (5, 'Chapter'), (6, 'Patent'), (8, 'Pre Print'), (7, 'Poster'), (4, 'Conference Paper'), (3, 'Publication')], default=1),
        ),
    ]
