# Generated by Django 3.1.7 on 2021-04-10 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECEapp', '0023_auto_20210411_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='doamin',
            field=models.CharField(choices=[('IT', 'IT'), ('MANAGERIAL', 'ANALYST'), ('ECE-CORE', 'ECE-CORE')], max_length=10),
        ),
        migrations.AlterField(
            model_name='people',
            name='year',
            field=models.IntegerField(choices=[(2, 'Second Year'), (5, 'M.TECH'), (3, 'Third Year'), (6, 'PHD'), (1, 'First Year'), (4, 'Final Year')]),
        ),
        migrations.AlterField(
            model_name='project',
            name='projecttype',
            field=models.IntegerField(choices=[(3, 'Publication'), (9, 'Research Internship  Report'), (6, 'Patent'), (8, 'Pre Print'), (1, 'Thsesis'), (2, 'Article'), (7, 'Poster'), (4, 'Conference Paper'), (5, 'Chapter')], default=1),
        ),
    ]
