# Generated by Django 3.1.7 on 2021-04-10 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECEapp', '0024_auto_20210411_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='company',
            name='doamin',
            field=models.CharField(choices=[('IT', 'IT'), ('ECE-CORE', 'ECE-CORE'), ('MANAGERIAL', 'ANALYST')], max_length=10),
        ),
        migrations.AlterField(
            model_name='company',
            name='role',
            field=models.CharField(choices=[('FULL-TIME', 'Full Time'), ('INTERNSHIP', 'Intern')], max_length=10),
        ),
        migrations.AlterField(
            model_name='people',
            name='year',
            field=models.IntegerField(choices=[(2, 'Second Year'), (4, 'Final Year'), (6, 'PHD'), (1, 'First Year'), (3, 'Third Year'), (5, 'M.TECH')]),
        ),
        migrations.AlterField(
            model_name='project',
            name='projecttype',
            field=models.IntegerField(choices=[(5, 'Chapter'), (9, 'Research Internship  Report'), (1, 'Thsesis'), (3, 'Publication'), (6, 'Patent'), (2, 'Article'), (7, 'Poster'), (4, 'Conference Paper'), (8, 'Pre Print')], default=1),
        ),
    ]
